### ISSUE TITLE
Some warnings with MATLAB R2023a

### ISSUE THREAD

**Issue by wollmich** [DionTimmermann/metas-unclib-matlab-wrapper-tests#7]
I've some warnings with MATLAB R2023a and METAS UncLib V2.7.0.
Using MATLAB R2018a I've no warnings.

See the attached test reports:

[2023-03-21-test-report-MATLAB-R2018a.xlsx](https://github.com/DionTimmermann/metas-unclib-matlab-wrapper-tests/files/11030642/2023-03-21-test-report-MATLAB-R2018a.xlsx)
[2023-03-21-test-report-MATLAB-R2023a.xlsx](https://github.com/DionTimmermann/metas-unclib-matlab-wrapper-tests/files/11030644/2023-03-21-test-report-MATLAB-R2023a.xlsx)

**Comment by DionTimmermann** [comment]
Oh, I see you have access to the current maltab version. I envy you! ;-) Unfortunately, I do not have access to that version, so I will would not be able to test changes manually.

I had added the warnings for two reasons:
1) I think it is helpful to the end user if the matlab wrapper of the uncLib provides error messages that follow the style & format that a matlab user expects. (This mostly relates to the use of technical terms and level of detail.)
2) Seeing which cases lead to which error messages helps to understand how matlab implemented a specific algorithm, which in turn makes it easier to write methods for the uncLib wrapper that behave the same way as native matlab functions. (This was very helpful for subsref and subsasgn.)

However, the reasons mentioned above do not necessitate that the error messages are actually identical, especially not across all matlab versions. 

I think the best solution is to by default disable the checks for identical error messages and add a parameter / global variable to enable theses checks for when they are needed (debugging and creating new code).

Do you agree?

**Comment by wollmich** [comment]
Yes

**Comment by DionTimmermann** [comment]
I have now added the global option as suggested. Since I do not have the newest MATLAB version, I could only do some limited tests. Please reopen if the problem is not fixed.

**Comment by wollmich** [comment]
I seems to work with MATLAB R2023a:


Matlab Version | R2023a |  
-- | -- | --
Date | 2023-04-06 |  
Time | 08:39 |  
  |   |  
Failed Tests | 0 | (Tests where the results differed.)
Warning | 0 | (Differences between error messages and tests where a difference was   accepted, but did not occur.)
Accepted Differences | 171 | (Accepted differences that occured.)
Passed Tests | 2118 | (Tests with the same result or the same error message.)
